---
functional:
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
non-functional:
  -Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей) 
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - Пользователь должен зарегистрироваться
  - Вход в систему с использованием учетных данных
  - Пользователь может создать игру и пригласить другого пользователя
  - Пользователь может установить ограничение по времени игры
  - Пользователь видит редактор и код соперника в режиме он-лайн
  - Пользователь может общаться в чате
  - Пользователь может проверить свое решение
  - Пользователь может переподключиться в игру
  - При победе высвечивается модальное окно с победителем
  - Пользователь может просматривать статистику профиля
  - Пользователь может настроить свой профиль
