---
functional:
  - Пользователь может зарегистрироваться
  - Вход для уже зарегистрированных пользователей с использованием email и пароля
  - Пользователь может создать игру и пригласить другого пользователя
  - Пользователь может изменить настройки игры под себя
  - Пользователь видит редактор и код соперника в режиме он-лайн
  - Пользователь может проверить свое решение
  - Пользователь может переподключиться в игру
  - При победе появляется модальное окно объявляющее о победе
  - Реализация общего чата
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - Восстановление пароля через email
  - Профиль пользователя с отображением имени, ранга, рейтинга и значка аватарки
  - Список игроков в лобби с указанием ранга и возможности взаимодействия
  - Пользователь может просматривать статистику профиля и сыгранные игры
  - Пользователь может настроить свой профиль(изменить автар, информацию о себе)
  - Модерацию чата для поддержания порядка
  - Раздел для просмотра текущих и предстоящих турниров
  - Регистрация и участие в турнирах
  - Система оповещений о предстоящих событиях
  - Раздел для просмотра историй игр, включая их результаты
  - Вкладки для отображения лидеров: за неделю, месяц и за всё время
  - Пользователь может сдаться во время игры
  - При поражении появляется модальное окно объявляющее о поражении
  - Пользователь может отправить запрос о реванше
  - Интуитивно понятный и удобный интерфейс с навигацией
  - Панель администратора для управления пользователями и контентом
  - Система банов пользователей
  - Система достижений и наград за различные активности
  - Интеграция с социальными сетями для более удобного доступа
